# Day 1 

In [ ]:
import torch

In [2]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [4]:
x = x.reshape(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [3]:
x.reshape(-1,3) #-1 get the dimension on its own but col = 4

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.randn(3,4)

tensor([[ 0.6215, -0.1611, -0.0446, -0.3826],
        [-1.2996,  0.6574,  0.4558,  0.1807],
        [-0.4144,  0.2532, -0.3931, -0.3555]])

In [8]:
 torch.zeros(2)

tensor([0., 0.])

In [9]:
x = torch.tensor([1.0,2,3,4])
y = torch.tensor([2,3,4,5])
x + y , x -y, x/y, x ** y

(tensor([3., 5., 7., 9.]),
 tensor([-1., -1., -1., -1.]),
 tensor([0.5000, 0.6667, 0.7500, 0.8000]),
 tensor([1.0000e+00, 8.0000e+00, 8.1000e+01, 1.0240e+03]))

In [10]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((x,y),dim = 0) # Row wise

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [11]:
torch.cat((x,y),dim = 1) # column wise 

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [12]:
x.sum()

tensor(66.)

In [13]:
a = torch.arange(3).reshape((3, 1)) 
b = torch.arange(2).reshape((1, 2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
z = torch.tensor([[0,1]]) # z = torch.tensor([0,1])
z.shape

torch.Size([1, 2])

In [15]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:

x,x[-1],x[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [28]:
Z = torch.zeros_like(y)  
print('id(Z):', id(Z))
Z[:] = x + y   # slicing refers to the previously allocated array y . 
print('id(Z):', id(Z))

id(Z): 1308191491872
id(Z): 1308191491872


In [30]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [36]:
a = torch.tensor([3.5])
a, a.item(),float(a),int(a) # a.item() coverts size tensor 1 to python scalar


(tensor([3.5000]), 3.5, 3.5, 3)

In [39]:
x > y


tensor([[ True,  True, False,  True],
        [ True,  True,  True, False],
        [False,  True,  True,  True]])

In [4]:
import os

os.makedirs(os.path.join('..', 'data'),exist_ok=True)   # '..' dir 1 step back './' same dir as file 
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example 
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [5]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


 ##### iloc vs loc 
 iloc is integer-location based indexing . Example : df.iloc[4:6] # selects row 4 to 6 
 
 loc is select specific rows and column names . Example df.loc[['E':, :'assist']]
 
 

In [56]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [59]:
inputs = pd.get_dummies(inputs,dummy_na = True)  #dummy_na=True makes a column for Nan
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [70]:
import torch
X,y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## Linear Algebra

In [6]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x **y 

(tensor(5.), tensor(6.), tensor(9.))

In [17]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

![Axis](../images/axis.jpg)

<h3><center>Axis Description</center></h3>

In [11]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [16]:
A_row = A.sum(axis=0)
A_row

tensor([40, 45, 50, 55])

In [19]:
A_col = A.sum(axis=1)
A_col, A_col.shape

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

In [23]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

### Dot Products

In [25]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [26]:
#Dot product same as torch.sum(x * y)
torch.sum(x * y)

tensor(6.)

In [ ]:
61